# Generated by Django 5.0.1 on 2024-01-30 09:13

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='designation',
            field=models.CharField(default=5454, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='services',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='website',
            field=models.CharField(default=datetime.datetime(2024, 1, 30, 9, 13, 21, 203131, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
