# Generated by Django 5.0.1 on 2024-01-30 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_name_seller_business_name_seller_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 1, 30, 9, 24, 58, 61006, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
