# Generated by Django 5.0.1 on 2024-01-30 09:38

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_seller_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='technology',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='linkedin',
            field=models.CharField(default=datetime.datetime(2024, 1, 30, 9, 38, 23, 87350, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='pannunber',
            field=models.CharField(default=datetime.datetime(2024, 1, 30, 9, 38, 39, 312347, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
