# Generated by Django 5.0.1 on 2024-01-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_technology_freelancer_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='pannunber',
            new_name='pan',
        ),
    ]
