# Generated by Django 5.0.1 on 2024-01-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_pannunber_freelancer_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='experience',
        ),
    ]
