# Generated by Django 5.0.1 on 2024-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_freelancer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
